<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.10.10" />
    <PackageVersion Include="FSharp.Core" Version="4.2.3" />
    <PackageVersion Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="1.0.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="NUnit" Version="3.11.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="3.13.0" />
    <PackageVersion Include="xunit" Version="2.3.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>
</Project>